# Generated by Django 4.2.13 on 2026-10-01 14:05
#
# Encaissements : numéro de bordereau (espèces), numéro du reçu de l'opérateur (paiement
# mobile), motif et référence élargie de compensation, réencaissement d'un chèque impayé.
# Chèques : échéancier (client, date de dépôt prévue), statut, décaissement d'un impayé.
# sp_enregistrement_encaissement v4 : paiement mobile accepté sur le numéro du reçu de
# l'opérateur (la vérification DistriPay reste faite quand la référence est une transaction).

from django.db import migrations, models
import django.db.models.deletion

from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0015_alter_client_fonction"),
        ("production", "0142_brouillon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_column="idclient",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cheques",
                to="customer.client",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="date_decaissement",
            field=models.DateField(blank=True, db_column="datedecaissement", null=True),
        ),
        migrations.AddField(
            model_name="cheque",
            name="date_depot",
            field=models.DateField(blank=True, db_column="datedepot", null=True),
        ),
        migrations.AddField(
            model_name="cheque",
            name="date_echeance",
            field=models.DateField(blank=True, db_column="dateecheance", null=True),
        ),
        migrations.AddField(
            model_name="cheque",
            name="montant_impaye",
            field=models.DecimalField(
                blank=True,
                db_column="montantimpaye",
                decimal_places=4,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="motif_decaissement",
            field=models.CharField(
                blank=True, db_column="motifdecaissement", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="observation",
            field=models.CharField(
                blank=True, db_column="observation", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="statut",
            field=models.CharField(
                choices=[
                    ("A_DEPOSER", "À déposer"),
                    ("ENCAISSE", "Encaissé"),
                    ("IMPAYE", "Impayé"),
                    ("REENCAISSE", "Réencaissé"),
                ],
                db_column="statut",
                default="ENCAISSE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="cheque_impaye",
            field=models.ForeignKey(
                blank=True,
                db_column="idchequeimpaye",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reencaissements",
                to="production.cheque",
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="motif_compensation",
            field=models.CharField(
                blank=True, db_column="motifcompensation", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="numero_bordereau",
            field=models.CharField(
                blank=True, db_column="numerobordereau", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="numero_recu_operateur",
            field=models.CharField(
                blank=True, db_column="numerorecuoperateur", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="reference_reencaissement",
            field=models.CharField(
                blank=True,
                db_column="referencereencaissement",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="encaissement",
            name="compte_compensation",
            field=models.CharField(
                blank=True, db_column="compte_compensation", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="encaissement",
            name="motifannulation",
            field=models.CharField(
                blank=True, db_column="motifannulation", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="encaissement",
            name="numerocheque",
            field=models.CharField(
                blank=True, db_column="numerocheque", max_length=50, null=True
            ),
        ),
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_enregistrement_encaissement",
                from_version=3,
                to_version=4,
            )
        ),
    ]
